### ISSUE TITLE
Installation fails with error

### ISSUE THREAD

**Issue by DeeBeeKay** [bartbutenaers/node-red-dashboard-2-ui-video#23]
Hello,

  I apologise if this is obvious.

  I am running node-RED in docker, on Debian 12. I am using Portainer to manage this container.

  I opened bash inside the container, and pasted the install command. This was the error:

```
ff90a3af7859:~$ npm install bartbutenaers/node-red-dashboard-2-ui-video
npm error code 128
npm error An unknown git error occurred
npm error command git --no-replace-objects ls-remote ssh://git@github.com/bartbutenaers/node-red-dashboard-2-ui-video.git
npm error ssh: Could not resolve hostname github.com: Try again
npm error fatal: Could not read from remote repository.
npm error
npm error Please make sure you have the correct access rights
npm error and the repository exists.
npm error A complete log of this run can be found in: /data/.npm/_logs/2024-11-05T17_33_38_859Z-debug-0.log
ff90a3af7859:~$ 
```

Is the above enough of a clue, or would you like the log file it talks about?

I continue to learn about Linux, and about containers, but my gut says this is about a port needing to be open somewhere, that isn't. Am I in the ballpark?

I thank you for any insights you may share.

**Comment by bartbutenaers** [comment]
Hi @DeeBeeKay,

From `Could not resolve hostname github.com` I would expect you have no access to github from your container.

I don't use docker myself because imho the extra layer makes things too complex for my personal use.  Issues like this one...

I see e.g. [here](https://github.com/docker/compose/issues/8488#issuecomment-903527077) a tip.  In case this doesn't help:  I would search for that error message in combination with the keword 'docker'.  And if you can't find anything, ask in the Node-RED forum.

Good luck!
Bart

**Comment by DeeBeeKay** [comment]
Thank you. If I find a good solution, I will come back and post it.

**Comment by DeeBeeKay** [comment]
Here is the solution for anyone who searches this.

As per @bartbutenaers's link above, it is necessary to explicitly add a working DNS to the docker container. Follow bart's link for an example of how to do this in docker.

In portainer, edit the container. You will find what you need in the Network tab of the container config. 

Redeploy the container, and the installation command will now work correctly. Note that you will need to restart the container again after the install.

**Comment by bartbutenaers** [comment]
Hi @DeeBeeKay,
Thanks for confirming here tgat the tip works!
